In [47]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "Housing.csv"

# Load the latest version
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "harishkumardatalab/housing-price-prediction",
  file_path,
)


In [2]:
df.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished


In [6]:
# X-> features, y -> target
X=df.drop('price',axis=1)
y=df['price']

In [ ]:
# numeric_features=["area","bedrooms","bathrooms","stories","parking"]
# categorical_features=["mainroad","guestroom","basement","hotwaterheating","airconditioning","prefarea",
#                       "furnishingstatus"]
num_features=X.select_dtypes(include=['int64']).columns
cat_features=X.select_dtypes(include=['object']).columns


bedrooms


In [8]:
# dividing the data into taraining and testing data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.2,random_state=42)
print(X_test)

     area  bedrooms  bathrooms  stories mainroad guestroom basement  \
316  5900         4          2        2       no        no      yes   
77   6500         3          2        3      yes        no       no   
360  4040         2          1        1      yes        no       no   
90   5000         3          1        2      yes        no       no   
493  3960         3          1        1      yes        no       no   
..    ...       ...        ...      ...      ...       ...      ...   
138  5000         3          1        3      yes        no       no   
62   6240         4          2        2      yes        no       no   
135  6000         3          2        4      yes        no       no   
128  5500         3          1        3      yes       yes       no   
528  3970         1          1        1       no        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
316              no              no        1       no      unfurnished  
7

In [30]:
# encoding categorical features
from sklearn.preprocessing import OneHotEncoder,StandardScaler
encoder=OneHotEncoder(drop="first")
X_train_cat=encoder.fit_transform(X_train[cat_features]).toarray()
X_test_cat=encoder.transform(X_test[cat_features]).toarray()

print(X_train_cat)

[[1. 1. 1. 0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 1. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 1. 0.]
 [1. 1. 1. 0. 0. 1. 1. 0.]
 [1. 0. 1. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 1. 0.]
 [1. 1. 0. 0. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 1. 0.]
 

In [31]:
# scaling numerical features
scaler=StandardScaler()
X_train_num=scaler.fit_transform(X_train[num_features])
X_test_num=scaler.transform(X_test[num_features])
print(X_train_num)

[[ 1.71256506e+00  1.37446594e+00 -4.19832101e-01  2.49756216e-01
   1.61888993e+00]
 [-3.63848639e-01  1.37446594e+00 -4.19832101e-01 -8.84553266e-01
  -7.18315398e-01]
 [-4.93624495e-01 -1.30083384e+00 -4.19832101e-01 -8.84553266e-01
  -7.18315398e-01]
 [ 3.30880809e+00  3.68160520e-02 -4.19832101e-01 -8.84553266e-01
   4.50287265e-01]
 [-3.74749810e-01  3.68160520e-02 -4.19832101e-01  1.38406570e+00
  -7.18315398e-01]
 [ 1.55683403e+00  3.68160520e-02  1.75929642e+00  2.49756216e-01
  -7.18315398e-01]
 [ 1.08964095e+00  3.68160520e-02 -4.19832101e-01 -8.84553266e-01
  -7.18315398e-01]
 [ 9.07954750e-01  3.68160520e-02 -4.19832101e-01  2.49756216e-01
  -7.18315398e-01]
 [-6.64928624e-01  3.68160520e-02 -4.19832101e-01 -8.84553266e-01
   1.61888993e+00]
 [ 6.74358210e-01  3.68160520e-02 -4.19832101e-01 -8.84553266e-01
  -7.18315398e-01]
 [-9.34862405e-01  1.37446594e+00 -4.19832101e-01  2.49756216e-01
  -7.18315398e-01]
 [ 6.43212004e-01  3.68160520e-02 -4.19832101e-01 -8.84553266e-01

In [32]:
# combining numerical and categorical features
import numpy as np
X_train_final=np.hstack([X_train_num,X_train_cat])
X_test_final=np.hstack([X_test_num,X_test_cat])

# Training

In [33]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train_final,y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


# Making Predictions

In [34]:
y_pred=model.predict(X_test_final)
print(y_pred)

[ 5741290.38646895  6374624.25790406  3361957.28727913  4186926.68454356
  3611181.05860653  3626550.26104513  5875457.91413702  7152350.4990356
  3428094.04291085  2883330.53958963  9182492.37721732  2785850.19866656
  2613464.7823272   3708543.65730293  3785824.19446901  6114586.64529665
  3008906.33348118  4294537.64313879  4672479.84507965  3875856.12793746
  4117158.98899666  6119705.23221326  2711125.11214226  5072600.63873187
  6455699.52781957  8144755.75164567  4091001.87607816  6410699.95281838
  8092484.30244822  3431069.28629995  6075830.14658311  3258210.05384523
  6961831.96586489  4329157.91604551  3408637.23686475  5818739.9311975
  6126806.69232331  3970131.99140126  2660767.96111797  4938639.53949456
  5292692.94743224  2987354.36517638  6353648.79502005  4249663.06983928
  4072501.09247509  3972332.49805583  6155724.95832018  4315288.01637555
  3865037.76404905  4026908.3354858   6781610.00062556  2934693.94233202
  4893640.18385118  4356825.18324225  3809529.9775152

# Model Evaluation

In [39]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
mae=mean_absolute_error(y_test,y_pred)
rmse=np.sqrt(mean_squared_error(y_test,y_pred))
r2=r2_score(y_test,y_pred)
print(f"MAE = {mae}")
print(f"RMSE = {rmse}")
print(f"R2 = {r2}")

MAE = 932640.4376620079
RMSE = 1251802.9261171806
R2 = 0.5503175979041736


In [ ]:
import pandas as pd
new_house = pd.DataFrame({
    "area": [3000],
    "bedrooms": [3],
    "bathrooms": [2],
    "stories": [2],
    "mainroad": ["yes"],
    "guestroom": ["no"],
    "basement": ["yes"],
    "hotwaterheating": ["no"],
    "airconditioning": ["yes"],
    "parking": [2],
    "prefarea": ["yes"],
    "furnishingstatus": ["furnished"]
})
new_cat = encoder.transform(new_house[["mainroad","guestroom","basement","hotwaterheating","airconditioning",
                                      "prefarea","furnishingstatus"]]).toarray()
new_num = scaler.transform(new_house[["area","bedrooms","bathrooms","stories","parking"]])

new_final = np.hstack([new_num, new_cat])

predicted_price = model.predict(new_final)
print("Predicted Price:", predicted_price[0])

Predicted Price: 6761071.072974191
